### ISSUE TITLE
(b1.4 - 13w01b) Missing texture

### ISSUE THREAD

**Issue by muzikbike** [NeRdTheNed/MC-TextureGen#21]
So during my research into the 13w02a-13w17a missing texture, I ended up stumbling upon a bug report which featured the missing texture in it. The problem was, this report was made in 1.4.6, several weeks before the texture pack reform was set to take place.

https://bugs.mojang.com/browse/MC-5094

Since I don't have a Mac and therefore cannot experience this bug in the wild, I decided to artificially execute it by deleting the texture for the book and quill. Sure enough, I got the equivalent result. But the book and quill was relatively new at the time, and "missing" still showed up even in the version it was added, so I decided to take measures into my own hands and delete the sun instead. Sure enough, it actually worked, and look -
![2021-09-17_22 46 31](https://user-images.githubusercontent.com/52297970/133858355-d8a15fc8-d8f9-4941-9642-9d8800904e9f.png)
It's *different!*

As I expected, the change was made from 13w01b to 13w02a:

![2021-09-17_22 48 36](https://user-images.githubusercontent.com/52297970/133858384-bc67dd99-2fa2-4003-8ac6-261c7e665421.png)
![2021-09-17_22 48 12](https://user-images.githubusercontent.com/52297970/133858388-f0daf0a3-acf0-4012-a515-ba3e9b346510.png)

I decided to go back and find the first version this was added in. My journey led to Beta 1.4 (Beta 1.3_01 just crash with a texture not found error when opening the world):
![2021-09-17_22 53 38](https://user-images.githubusercontent.com/52297970/133858431-c71a22fd-d8ef-49a2-b72a-469a98842b5d.png)
![2021-09-17_22 56 49](https://user-images.githubusercontent.com/52297970/133858433-4ddc610e-acbc-408d-a3ba-4f41eb408392.png)

So here's a new texture that can (probably very easily) be added to the list of generation candidates, and also an obscure new facet of Minecraft history for me to document...

**Comment by NeRdTheNed** [comment]
@muzikbike Thank you so much for documenting this! I completely failed to do any research myself, lesson learned for next time. I'm not confident that my "missing texture" text generator is accurate, especially given the second bug report you found where the text is clearly anti-aliased, when my text generator seemingly does not generate textures that way. It might be a bit before I commit a fix for that, and a new generator for this new texture, because I really need to figure out why this discrepancy occurs.

**Comment by NeRdTheNed** [comment]
...actually, now I'm not sure about anything, because I've found [MC-7208](https://bugs.mojang.com/browse/MC-7208), which [clearly shows](https://bugs.mojang.com/secure/attachment/18353/Picture%206.png) the same generated texture as the one I've been generating, displayed on a Mac, as well as another unique texture variation!

- @muzikbike Here's a new unique variation from that bug report
![stitched_items_out-0](https://user-images.githubusercontent.com/41816363/133868008-3e86dc50-5a79-4e55-94ed-86a12a4d4254.png)
